### ISSUE TITLE
Lingo New gives failing .lingo file

### ISSUE THREAD

**Issue by BlakeMScurr** [codelingo/lingo#230]
```
lexicons:
- codelingo/common as _
tenets:
- name: find-funcs
  doc: Example tenet that finds all functions.
  comment: This is a function, but you probably already knew that.
  match: |
    <func
```

This doesn't work because the query to the engine won't specify an AST lexicon. This will only be valid for searching on an already ingested repository.
