### ISSUE TITLE
Spinner not showing

### ISSUE THREAD

**Issue by BlakeMScurr** [codelingo/lingo#250]
`time lingo search .lingo` doesn't show a spinner for a search on cloud with this .lingo file:

```
lexicons:
- codelingo/php
- codelingo/git
tenets:
- name: find-funcs
  doc: Example tenet that finds all functions.
  comment: This is a function, but you probably already knew that.
  match: 
    git.repo:
      owner: "symfony"
      name: "symfony"
      host: "https://github.com"
      git.commit:
        sha: "e4bfc40d0e58835b0b1c8d5d50065d3ba4ef3c90"
        php.project:
          <php.stmt_function[:]
```

on client commit 6391e5499d3e9a5a693ca0f36720a2d199cc35ee
