### ISSUE TITLE
default .lingo broken

### ISSUE THREAD

**Issue by waigani** [codelingo/lingo#8]
The following .lingo is generated when you run `lingo init`:

``` yaml
lexicons:
- codelingo/common as _
tenets:
- name: find-funcs
  doc: Example tenet that finds all functions.
  comment: This is a function, but you probably already knew that.
  match: |2
      <func
# Add and configure tenets following these guidelines: http://codelingo/lingo/getting-started#the-lingo-file.
```

The query is broken because there are four spaces instead of two in front of "<func". The parser should be able to handle varying number of spaces.

"|2" is generated from the yaml parser - it doesn't break anything, but it's not needed and will confuse beginners.
